version: "3"
 
services:
  cardano-ism:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000
      - 8000
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cardano.rule=Host(`cardanoism.com`)"
      - "traefik.http.routers.cardano.entrypoints=websecure"
      - "traefik.http.routers.cardano.tls.certResolver=letsencrypt"
      - "traefik.http.services.cardano.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.cardano.headers.customRequestHeaders.Upgrade=websocket"
      - "traefik.http.middlewares.cardano.headers.customResponseHeaders.Upgrade=websocket"
      - "traefik.http.middlewares.cardano.headers.customRequestHeaders.Connection=Upgrade"
      - "traefik.http.middlewares.cardano.headers.customResponseHeaders.Connection=Upgrade"
networks:
  dokploy-network:
    external: true