version: "3"
 
services:
  cardano-ism:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000
      - 8000
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`cardanoism.com`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certResolver=letsencrypt"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
      - "traefik.http.routers.backend.rule=Host(`cardanoism.com`) && PathPrefix(`/_event`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certResolver=letsencrypt"
      - "traefik.http.services.backend.loadbalancer.server.port=8000"
networks:
  dokploy-network:
    external: true