version: "3"
 
services:
  cardano-ism:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000
      - 8000
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cardano.rule=Host(`cardanoism.com`)"
      - "traefik.http.routers.cardano.entrypoints=websecure"
      - "traefik.http.routers.cardano.tls.certResolver=letsencrypt"
      - "traefik.http.services.cardano.loadbalancer.server.port=3000"
      - "traefik.http.routers.event-service.rule=PathPrefix(`/_event`)"
      - "traefik.http.routers.event-service.entrypoints=websecure"
      - "traefik.http.routers.event-service.middlewares=cardano-headers"
      - "traefik.http.services.event-service.loadbalancer.server.port=8000"
      - "traefik.http.middlewares.cardano-headers.headers.customrequestheaders.Upgrade=websocket"
      - "traefik.http.middlewares.cardano-headers.headers.customrequestheaders.Connection=Upgrade"
networks:
  dokploy-network:
    external: true