server {
    listen 80;
    listen [::]:80;
    server_name frontend;

    # Docker DNS
    resolver 127.0.0.11 ipv6=off;

    # ★ 変数に入れる（超重要）
    set $backend http://backend:8000;

    location /_event {
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_pass $backend;
    }

    location /ping {
        proxy_set_header Host $host;
        proxy_pass $backend;
    }

    location /_upload {
        proxy_set_header Host $host;
        proxy_pass $backend;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}

