USE cardanoism;

CREATE TABLE `proposals_new` (
  `id` int(11) NOT NULL,
  `uuid` char(36) DEFAULT NULL,
  `fund_uuid` char(36) DEFAULT NULL,
  `campaign_uuid` char(36) DEFAULT NULL,
  `user_id` int(11) DEFAULT NULL,
  `fund_id` int(11) DEFAULT NULL,
  `challenge_id` int(11) DEFAULT NULL,
  `title` text DEFAULT NULL,
  `title_ja` text DEFAULT NULL,
  `ideascale_link` varchar(255) DEFAULT NULL,
  `ideascale_user` varchar(100) DEFAULT NULL,
  `ideascale_id` varchar(100) NOT NULL,
  `amount_requested` int(11) DEFAULT NULL,
  `amount_received` int(11) DEFAULT NULL,
  `project_status` varchar(100) DEFAULT NULL,
  `funding_status` varchar(100) DEFAULT NULL,
  `yes_votes_count` int(20) DEFAULT NULL,
  `no_votes_count` int(20) DEFAULT NULL,
  `abstain_votes_count` int(20) DEFAULT NULL,
  `unique_wallets` int(11) DEFAULT NULL,
  `problem` text DEFAULT NULL,
  `problem_ja` text DEFAULT NULL,
  `solution` text DEFAULT NULL,
  `solution_ja` text DEFAULT NULL,
  `currency_symbol` char(3) DEFAULT NULL,
  `currency` char(5) DEFAULT NULL,
  `alignment_score` float DEFAULT NULL,
  `feasibility_score` float DEFAULT NULL,
  `auditability_score` float DEFAULT NULL,
  `tags` text DEFAULT NULL,
  `slug` text DEFAULT NULL,
  PRIMARY KEY (`ideascale_id`),
  KEY `proposals_challenges_FK` (`challenge_id`) USING BTREE,
  KEY `proposals_funds_FK` (`fund_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;