USE cardanoism;

CREATE TABLE `proposals_new` (
  `id` int(11) DEFAULT NULL,
  `uuid` char(36) NOT NULL,
  `fund_uuid` char(36) DEFAULT NULL,
  `campaign_uuid` char(36) DEFAULT NULL,
  `user_id` int(11) DEFAULT NULL,
  `user_name` varchar(100) DEFAULT NULL,
  `projectcatalyst_link` varchar(2038) DEFAULT NULL,
  `fund_id` int(11) DEFAULT NULL,
  `challenge_id` int(11) DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  `title_ja` varchar(255) DEFAULT NULL,
  `ideascale_link` varchar(255) DEFAULT NULL,
  `ideascale_user` varchar(100) DEFAULT NULL,
  `ideascale_id` varchar(100) DEFAULT NULL,
  `amount_requested` int(11) DEFAULT NULL,
  `amount_received` int(11) DEFAULT NULL,
  `project_status` varchar(100) DEFAULT NULL,
  `funding_status` varchar(100) DEFAULT NULL,
  `yes_votes_count` int(20) DEFAULT NULL,
  `no_votes_count` int(20) DEFAULT NULL,
  `abstain_votes_count` int(20) DEFAULT NULL,
  `unique_wallets` int(11) DEFAULT NULL,
  `problem` text DEFAULT NULL,
  `problem_ja` text DEFAULT NULL,
  `solution` text DEFAULT NULL,
  `solution_ja` text DEFAULT NULL,
  `currency_symbol` char(3) DEFAULT NULL,
  `currency` char(5) DEFAULT NULL,
  `alignment_score` float DEFAULT NULL,
  `feasibility_score` float DEFAULT NULL,
  `auditability_score` float DEFAULT NULL,
  `tags` text DEFAULT NULL,
  `slug` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`uuid`),
  KEY `proposals_new_fund_uuid_IDX` (`fund_uuid`,`funding_status`,`yes_votes_count`,`campaign_uuid`) USING BTREE,
  FULLTEXT KEY `proposals_new_user_name_IDX` (`user_name`,`title`,`title_ja`,`problem`,`problem_ja`,`solution`,`solution_ja`,`tags`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;