-- 015_governance_actions.sql
-- Governance actions table (Cardano on-chain governance proposals)

CREATE TABLE IF NOT EXISTS governance_actions (
    id               INT           NOT NULL AUTO_INCREMENT,
    proposal_id      VARCHAR(255)  NOT NULL,
    proposal_tx_hash VARCHAR(64)   NOT NULL,
    proposal_index   TINYINT       NOT NULL DEFAULT 0,
    proposal_type    VARCHAR(50)   NOT NULL,
    proposed_epoch   INT           DEFAULT NULL,
    ratified_epoch   INT           DEFAULT NULL,
    enacted_epoch    INT           DEFAULT NULL,
    dropped_epoch    INT           DEFAULT NULL,
    expired_epoch    INT           DEFAULT NULL,
    expiration       INT           DEFAULT NULL,
    block_time       DATETIME      DEFAULT NULL,
    deposit          BIGINT        DEFAULT NULL,
    return_address   VARCHAR(255)  DEFAULT NULL,
    meta_url         TEXT          DEFAULT NULL,
    meta_hash        VARCHAR(64)   DEFAULT NULL,
    meta_is_valid    TINYINT(1)    DEFAULT NULL,
    title            TEXT          DEFAULT NULL,
    `abstract`       MEDIUMTEXT    DEFAULT NULL,
    motivation       MEDIUMTEXT    DEFAULT NULL,
    rationale        MEDIUMTEXT    DEFAULT NULL,
    references_json  LONGTEXT      DEFAULT NULL,
    title_ja         TEXT          DEFAULT NULL,
    abstract_ja      MEDIUMTEXT    DEFAULT NULL,
    motivation_ja    MEDIUMTEXT    DEFAULT NULL,
    rationale_ja     MEDIUMTEXT    DEFAULT NULL,
    fetched_at       DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_proposal_id (proposal_id),
    KEY idx_type       (proposal_type),
    KEY idx_epoch      (proposed_epoch),
    KEY idx_block_time (block_time),
    KEY idx_expiration (expiration)
);
